package com.integration.zoy.config;

import javax.annotation.Generated;

import io.swagger.v3.oas.annotations.OpenAPIDefinition;
import io.swagger.v3.oas.annotations.enums.SecuritySchemeType;
import io.swagger.v3.oas.annotations.info.Info;
import io.swagger.v3.oas.annotations.security.SecurityScheme;

@Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen")
@OpenAPIDefinition(info = @Info(title = "Zoy Admin API", version = "v1"))
@SecurityScheme(
    name = "basicAuth",
    type = SecuritySchemeType.HTTP,
    scheme = "basic"
)
public class SwaggerDocumentationConfig {

//    @Bean
//    public OpenAPI openApi() {
//        return new OpenAPI()
//            .info(new Info()
//                .title("Notification API 3.0")
//                .description("No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)")
//                .termsOfService("")
//                .version("1.0.11")
//                .license(new License()
//                    .name("")
//                    .url("http://unlicense.org"))
//                .contact(new io.swagger.v3.oas.models.info.Contact()
//                    .email("mydbq.com")));
//    }

}
